/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContextMenu: typeof import('./components/AppContextMenu.vue')['default']
    AppIcon: typeof import('./components/icons/AppIcon.vue')['default']
    ApplicationConfirmationDialog: typeof import('./components/layout/ApplicationConfirmationDialog.vue')['default']
    ApplicationDialog: typeof import('./components/layout/ApplicationDialog.vue')['default']
    ApplicationWindow: typeof import('./components/layout/ApplicationWindow.vue')['default']
    DesktopHeader: typeof import('./components/layout/DesktopHeader.vue')['default']
    DesktopLayout: typeof import('./components/layout/DesktopLayout.vue')['default']
    MonacoEditor: typeof import('./components/editor/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VustActionMenu: typeof import('./components/ui/VustActionMenu.vue')['default']
    VustAlert: typeof import('./components/ui/VustAlert.vue')['default']
    VustBrandLogo: typeof import('./components/brand/VustBrandLogo.vue')['default']
    VustBreadcrumb: typeof import('./components/ui/VustBreadcrumb.vue')['default']
    VustBreadcrumbItem: typeof import('./components/ui/VustBreadcrumbItem.vue')['default']
    VustButton: typeof import('./components/ui/VustButton.vue')['default']
    VustCard: typeof import('./components/ui/VustCard.vue')['default']
    VustCheckbox: typeof import('./components/ui/VustCheckbox.vue')['default']
    VustDateTimeRangePicker: typeof import('./components/ui/VustDateTimeRangePicker.vue')['default']
    VustDescriptions: typeof import('./components/ui/VustDescriptions.vue')['default']
    VustDialog: typeof import('./components/ui/VustDialog.vue')['default']
    VustDrawer: typeof import('./components/ui/VustDrawer.vue')['default']
    VustEmpty: typeof import('./components/ui/VustEmpty.vue')['default']
    VustFormItem: typeof import('./components/ui/VustFormItem.vue')['default']
    VustGlassSurface: typeof import('./components/ui/VustGlassSurface.vue')['default']
    VustIcon: typeof import('./components/icons/VustIcon.vue')['default']
    VustInput: typeof import('./components/ui/VustInput.vue')['default']
    VustLoading: typeof import('./components/ui/VustLoading.vue')['default']
    VustMenu: typeof import('./components/ui/VustMenu.vue')['default']
    VustModal: typeof import('./components/ui/VustModal.vue')['default']
    VustPagination: typeof import('./components/ui/VustPagination.vue')['default']
    VustSelect: typeof import('./components/ui/VustSelect.vue')['default']
    VustSelectionBar: typeof import('./components/ui/VustSelectionBar.vue')['default']
    VustSwitch: typeof import('./components/ui/VustSwitch.vue')['default']
    VustTable: typeof import('./components/ui/VustTable.vue')['default']
    VustTabs: typeof import('./components/ui/VustTabs.vue')['default']
    VustTag: typeof import('./components/ui/VustTag.vue')['default']
    VustToast: typeof import('./components/ui/VustToast.vue')['default']
    VustTooltip: typeof import('./components/ui/VustTooltip.vue')['default']
  }
}
